name: Deploy Node.js app to Azure Web App - CredHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: npm install, test (optional)
        run: |
          npm install
          npm run test --if-present
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D0B9928D15404BE582F43CD5E410FA49 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C95A53412319468F8D705ECD1C93756B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_427A9C84C598423881D0D31D9125AC98 }}
      - name: Zip project files
        run: zip -r deploy.zip . -x node_modules/\* \*.git\* \*.github\* \*test\* \*README.md
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CredHub'
          slot-name: 'Production'
          package: deploy.zip
